name: Build and Deploy to OpenShift

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Login to OpenShift
      env:
        OPENSHIFT_SERVER: ${{ secrets.OCP_SERVER }}
        OPENSHIFT_TOKEN: ${{ secrets.OCP_TOKEN }}
      run: |
        curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
        tar -xzf openshift-client-linux.tar.gz
        sudo mv oc kubectl /usr/local/bin/
        oc login --token=$OPENSHIFT_TOKEN --server=$OPENSHIFT_SERVER --insecure-skip-tls-verify

    - name: Login to internal OpenShift registry
      run: |
        docker login -u kubeadmin -p $(oc whoami -t) image-registry.openshift-image-registry.svc:5000

    - name: Build and push image to OpenShift registry
      run: |
        docker build -t flask-app .
        docker tag flask-app image-registry.openshift-image-registry.svc:5000/flask-demo/flask-app:latest
        docker push image-registry.openshift-image-registry.svc:5000/flask-demo/flask-app:latest

    - name: Restart deployment in OpenShift
      run: |
        oc rollout restart deployment/flask-app -n flask-demo
